### ISSUE TITLE
any update?

### ISSUE THREAD

**Issue by carl1961** [Markus98/Tambot#1]
Awesome Work, saw your youtube, was hoping to get more info to make your robot checker, yours is the first I have seen from all I found that kings their checkers

**Comment by Markus98** [comment]
Hi and thanks! This is a project I worked on while in university and there will be no more updates to it. There is additional documentation, but I think that is on a the university hosted wiki site, which you need a university account to access (probably can be found somewhere [here](https://mycourses.aalto.fi/course/view.php?id=31372&section=4)).

There are many things in this project that I would do differently now, but since it was just a course project, it will remains the way that it is  :). Many of the parts we made for this robot were based on the components we had available at the workshop, so I would not recommend building this exact robot for yourself. I do not even have access to the files anymore. 

If you are interested on how it worked physically:
- The pieces each have a magnet in them.
- All of the board squares have a reed switch below them to recognize where the pieces are.
- The arm is controlled by stepper motors fox XY movements and servos to pick the pieces up with a magnet.
- A raspberry pi 3b controls the electronics and handles the game logic.
- The board was laser cut and other components are off the shelf or self designed + 3D printed. 

If you have any more questions then feel free to ask them here.

**Comment by carl1961** [comment]
Thanks for your response. I think I can figure most by reading your code, I did search 8x8 array and think I got that figured out, although it was for playing chess. 

Learning 8x8 array (chess)
https://acboard.blogspot.com/

https://mtifall10.wordpress.com/2010/12/10/magnetic-sensing-chessboard/

Is it ok to fork your Tambot and I update my progress there?

**Comment by Markus98** [comment]
Of course. Just know that the code is not optimized that well for performance.

**Comment by carl1961** [comment]
Thanks, I made a z axis with gears and MGN9 linear rail. by watching your video, also working on the printer frame, from your video I seen to get like I need 500mm for a  x MGN12 linear rail, and close to 600mm y MGN12 linear rail to allow enough room for home area.  https://github.com/carl1961/Tambot-Checkers
